version: '3.4'

services:
  flight-search-front:
    image: flight-search-front
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173